
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: lmy456258
      POSTGRES_DB: blog
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  

